// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entity "url-shortener/m/pkg/entity"
	"url-shortener/m/pkg/uniqueEntityId"

	mock "github.com/stretchr/testify/mock"
)

// ShortenedUrlRepository is an autogenerated mock type for the ShortenedUrlRepository type
type ShortenedUrlRepository struct {
	mock.Mock
}

// FindBySlug provides a mock function with given fields: slug
func (_m *ShortenedUrlRepository) FindBySlug(slug string) (*entity.ShortenedUrl, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.ShortenedUrl
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.ShortenedUrl, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.ShortenedUrl); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ShortenedUrl)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserId provides a mock function with given fields: userId
func (_m *ShortenedUrlRepository) FindByUserId(userId uniqueEntityId.ID) ([]*entity.ShortenedUrl, error) {
	ret := _m.Called(userId)

	var r0 []*entity.ShortenedUrl
	if rf, ok := ret.Get(0).(func(uniqueEntityId.ID) []*entity.ShortenedUrl); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ShortenedUrl)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uniqueEntityId.ID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: shortenedUrl
func (_m *ShortenedUrlRepository) Save(shortenedUrl *entity.ShortenedUrl) error {
	ret := _m.Called(shortenedUrl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.ShortenedUrl) error); ok {
		r0 = rf(shortenedUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id, userId
func (_m *ShortenedUrlRepository) Delete(id uint64, userId uniqueEntityId.ID) error {
	ret := _m.Called(id, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uniqueEntityId.ID) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShortenedUrlRepository creates a new instance of ShortenedUrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenedUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenedUrlRepository {
	mock := &ShortenedUrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
