// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	"time"
	entity "kazdel/pkg/entity"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ShortenedUrlRepository is an autogenerated mock type for the ShortenedUrlRepository type
type ShortenedUrlRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id, userId
func (_m *ShortenedUrlRepository) Delete(id uint64, userId uuid.UUID) error {
	ret := _m.Called(id, userId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uuid.UUID) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExpired provides a mock function with given fields: t
func (_m *ShortenedUrlRepository) DeleteExpired(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindBySlug provides a mock function with given fields: slug
func (_m *ShortenedUrlRepository) FindBySlug(slug string) (*entity.ShortenedUrl, error) {
	ret := _m.Called(slug)

	if len(ret) == 0 {
		panic("no return value specified for FindBySlug")
	}

	var r0 *entity.ShortenedUrl
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entity.ShortenedUrl, error)); ok {
		return rf(slug)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.ShortenedUrl); ok {
		r0 = rf(slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ShortenedUrl)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserId provides a mock function with given fields: userId
func (_m *ShortenedUrlRepository) FindByUserId(userId uuid.UUID) ([]*entity.ShortenedUrl, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserId")
	}

	var r0 []*entity.ShortenedUrl
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]*entity.ShortenedUrl, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []*entity.ShortenedUrl); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ShortenedUrl)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserIdPaginated provides a mock function with given fields: userId, search, page, limit
func (_m *ShortenedUrlRepository) FindByUserIdPaginated(userId uuid.UUID, search string, page int, limit int) ([]*entity.ShortenedUrl, int, error) {
	ret := _m.Called(userId, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserIdPaginated")
	}

	var r0 []*entity.ShortenedUrl
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int, int) ([]*entity.ShortenedUrl, int, error)); ok {
		return rf(userId, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int, int) []*entity.ShortenedUrl); ok {
		r0 = rf(userId, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ShortenedUrl)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, int, int) int); ok {
		r1 = rf(userId, search, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(uuid.UUID, string, int, int) error); ok {
		r2 = rf(userId, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: shortenedUrl
func (_m *ShortenedUrlRepository) Save(shortenedUrl *entity.ShortenedUrl) error {
	ret := _m.Called(shortenedUrl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.ShortenedUrl) error); ok {
		r0 = rf(shortenedUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: shortenedUrl
func (_m *ShortenedUrlRepository) Update(shortenedUrl *entity.ShortenedUrl) error {
	ret := _m.Called(shortenedUrl)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.ShortenedUrl) error); ok {
		r0 = rf(shortenedUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShortenedUrlRepository creates a new instance of ShortenedUrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenedUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenedUrlRepository {
	mock := &ShortenedUrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
