// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "kazdel/pkg/entity/dto"

	entity "kazdel/pkg/entity"

	mock "github.com/stretchr/testify/mock"
)

// UrlVisitRepository is an autogenerated mock type for the UrlVisitRepository type
type UrlVisitRepository struct {
	mock.Mock
}

// GetStatsByUrlId provides a mock function with given fields: ctx, urlId
func (_m *UrlVisitRepository) GetStatsByUrlId(ctx context.Context, urlId uint64) (*dto.UrlStats, error) {
	ret := _m.Called(ctx, urlId)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsByUrlId")
	}

	var r0 *dto.UrlStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*dto.UrlStats, error)); ok {
		return rf(ctx, urlId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *dto.UrlStats); ok {
		r0 = rf(ctx, urlId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UrlStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, urlId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, visit
func (_m *UrlVisitRepository) Save(ctx context.Context, visit *entity.UrlVisit) error {
	ret := _m.Called(ctx, visit)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UrlVisit) error); ok {
		r0 = rf(ctx, visit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUrlVisitRepository creates a new instance of UrlVisitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlVisitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlVisitRepository {
	mock := &UrlVisitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
